import { render, ui } from '@tenoxui-lib'
import { styles, externalCSS, fonts } from '@/styles'
import { extractCSS } from '../extractCSS'
import { config } from '@/design'

export const generateHTML = async (htmlContent: string): Promise<string> => {
  const temp = document.createElement('div')
  temp.innerHTML = htmlContent

  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${config.name || 'Generated by Gambaree'}</title>
    ${fonts
      .map(
        (font) =>
          `<link href="${document.querySelector<HTMLLinkElement>(`link#${font}`)?.href}" rel="stylesheet"/>`
      )
      .join('\n')}
    <style>
      ${(await extractCSS(externalCSS)).join('\n')}
      ${ui.render(styles)}
      ${render(temp)}
    </style>
  </head>
  <body>
    ${temp.innerHTML}
  </body>
</html>`
}
